#!/usr/bin/env python3
import sys, os, re, pickle
from collections import defaultdict

#-----------------------------------------------------#
#--------------Error Messages-------------------------#
#-----------------------------------------------------#
if not os.path.exists(".grip"):
    print("grip-add: error: grip repository directory .grip not found", file=sys.stderr)
    sys.exit(1)
    
if len(sys.argv) == 1:
    print("usage: grip-add <filenames>", file=sys.stderr)
    sys.exit(1)

#-----------------------------------------------------#
#--------------Processing files ----------------------#
#-----------------------------------------------------#
'''
    contents: 
        '@Changed': [filename1, filename2]
        filename: [staged, file content]
'''
contents = defaultdict(list)
index_path = '.grip/index'
if os.path.exists(index_path):
    index = open(index_path, 'rb')
    contents = pickle.load(index)

for filename in sys.argv[1:]:
    if re.match(r"[a-zA-Z0-9.\-_]+", filename).group() != filename:
        print(f"grip-add: error: invalid filename '{filename}'", file=sys.stderr)
        sys.exit(1)
    if filename not in contents and not os.path.exists(filename):
        print(f"grip-add: error: can not open '{filename}'", file=sys.stderr)
        sys.exit(1)
    
    #read added files content
    if os.path.exists(filename):
        content = open(filename, 'r').read()
    else:
        content = None

    if filename in contents and content == contents[filename][0]:
        continue

    contents[filename] = [content]
    if filename not in contents['@Changed']:   
        contents['@Changed'].append(filename)
#-----------------------------------------------------#
#--------------Save files to  index-------------------#
#-----------------------------------------------------#
index = open(index_path, 'wb')
pickle.dump(contents, index)
index.close()