#!/usr/bin/env python3
import sys, os, re, pickle, argparse
#-----------------------------------------------------#
#--------------Error Messages-------------------------#
#-----------------------------------------------------#
if not os.path.exists(".grip"):
	print("grip-checkout: error: grip repository directory .grip not found", file=sys.stderr)
	sys.exit(1)

BRANCH_PATH = '.grip/logs/refs/heads'
if not os.path.exists(BRANCH_PATH):
	print(f"grip-checkout: error: this command can not be run until after the first commit", file=sys.stderr)
	sys.exit(1)

parser = argparse.ArgumentParser(
	usage='grip-checkout <branch>',
	add_help=False
)
parser.add_argument('branch', nargs='?')
args = parser.parse_args()

#-----------------------------------------------------#
#--------------Checkout branches----------------------#
#-----------------------------------------------------#
