#!/usr/bin/env python3
import sys, os, re, pickle
#-----------------------------------------------------#
#--------------Error Messages-------------------------#
#-----------------------------------------------------#
if not os.path.exists(".grip"):
	print("grip-status: error: grip repository directory .grip not found", file=sys.stderr)
	sys.exit(1)
	
if len(sys.argv) != 1:
	print("usage: grip-status", file=sys.stderr)
	sys.exit(1)

#-----------------------------------------------------#
def readLog(n: int):
	"""
		Test if ./grip/logs/HEAD exist;
		return prefer, this id, commit_num, message
	"""
	pre_id, curr_id, num, message = '', '', -1, ''
	log_path = ".grip/logs/HEAD"
	if os.path.exists(".grip/logs/HEAD"):
		log = open(log_path, 'r').readlines()
		pre_info, commit_message = log[n].split(':')

		pre_info = pre_info.split()
		pre_id, curr_id = int(pre_info[0]), int(pre_info[1])
		
		num, message = re.findall(r"(\d+)\s(.*)", commit_message.strip())[0]

	return pre_id, curr_id, int(num), message
#-----------------------------------------------------#
#------------------Load Files-------------------------#
#-----------------------------------------------------#
curr_files, index_files, repo_files = set(), set(), set()
for filename in os.listdir():
	if re.match(r"[a-zA-Z0-9][a-zA-Z0-9.\-_]*", filename):
		curr_files.add(filename)

INDEX_PATH = '.grip/index'
if os.path.exists(INDEX_PATH):
	index = open(INDEX_PATH, 'rb')
	contents = pickle.load(index)
	index_files = contents['@Files']

log_num = readLog(-1)[2]
REPO_PATH = os.path.join('.grip/objects', f'{log_num}')
if os.path.exists(REPO_PATH):
	for filename in os.listdir(REPO_PATH):
		repo_files.add(filename)

files = curr_files.union(index_files, repo_files)
	
#-----------------------------------------------------#
#---------------Check Files Status--------------------#
#-----------------------------------------------------#
def check_status(filename, contents, index_files: set, curr_files: set, repo_files: set):
	#Untracked
	if filename not in index_files.union(repo_files):
		print(f'{filename} - untracked');	return
	
	#Deleted
	if filename not in index_files.union(curr_files):
		print(f'{filename} - file deleted, deleted from index');	return

	if filename not in index_files:
		print(f'{filename} - deleted from index'); return

	if filename not in curr_files:
		if filename not in repo_files:
			print(f'{filename} - added to index, file deleted'); return
		else:
			print(f'{filename} - file deleted'); return

	index_content = contents[filename]
	curr_content = open(filename, 'r').read()

	#Existed both curr and index not repo
	repo_path = os.path.join(REPO_PATH, filename)
	if not os.path.exists(repo_path):
		if index_content[0] != curr_content: #Changed
			print(f'{filename} - added to index, file changed'); return
		else:
			print(f'{filename} - added to index'); return
	
	#Existed both curr, index and repo
	repo_content = open(repo_path, 'r').read()
	if index_content[0] != curr_content: #Changed
		if index_content[0] != repo_content:
			print(f'{filename} - file changed, different changes staged for commit'); return
		else:
			print(f'{filename} - file changed, changes not staged for commit'); return
	else: #Not Changed
		if index_content[0] != repo_content:
			print(f'{filename} - file changed, changes staged for commit'); return
		else:
			print(f'{filename} - same as repo'); return

if os.path.exists(INDEX_PATH):
	index = open(INDEX_PATH, 'rb')
	contents = pickle.load(index)
	index_files = contents['@Files']
	
	for filename in sorted(files):
		check_status(filename, contents, index_files, curr_files, repo_files)
	
else:
	for filename in files:
		print(f'{filename} - untracked')