#!/usr/bin/env python3
import sys, os

#-----------------------------------------------------#
#--------------Error Messages-------------------------#
#-----------------------------------------------------#
if len(sys.argv) != 1:
	print("usage: grip-init", file=sys.stderr)
	sys.exit(1)
if os.path.exists(".grip"):
	print("grip-init: error: .grip already exists", file=sys.stderr)
	sys.exit(1)


#-----------------------------------------------------#
#--------------Creates folders------------------------#
#-----------------------------------------------------#
os.mkdir(".grip")
print("Initialized empty grip repository in .grip")